import pandas as pd
import asyncio
import os
from utils.time_utils import get_utc_now

class DataHandler:
    """
    Protocol 9.0: Async Data Ingestion.
    Reads the CSV generated by the live feed and serves it to the strategy.
    Implements a 'Buffer' to prevent reading disk on every millisecond tick.
    """
    def __init__(self, symbol, data_file_path):
        self.symbol = symbol
        self.file_path = data_file_path
        self.df = None
        self.last_update = None
        self._running = False

    async def start_buffer(self):
        """
        Background task that watches the CSV file for updates.
        """
        self._running = True
        print(f"   ⚡ Async Buffer: Started for {self.symbol}")
        
        while self._running:
            try:
                if os.path.exists(self.file_path):
                    # Fast read of the CSV
                    new_df = pd.read_csv(self.file_path)
                    
                    # Basic sanitization
                    if not new_df.empty:
                        # Ensure 'Datetime' is datetime object
                        if 'Datetime' in new_df.columns:
                            new_df['Datetime'] = pd.to_datetime(new_df['Datetime'])
                        
                        self.df = new_df
                        self.last_update = get_utc_now()
            except Exception as e:
                print(f"   ⚠️ Buffer Error ({self.symbol}): {e}")
            
            # Check every 1 second (decoupled from strategy speed)
            await asyncio.sleep(1)

    async def get_latest(self):
        """
        Returns the latest dataframe from memory.
        """
        return self.df
